-- Migracija 009: Seed tekstovi za rang test (recenice, citati, price kategorije)
-- Minimalno 20 tekstova po kategoriji da seeded RNG uvek ima izbor

INSERT INTO text_pool (content_lat, content_cyr, content_easy, category, difficulty, is_active) VALUES

-- RECENICE — lake
('Sunce sija iznad planine i nebo je vedro i plavo.', 'Сунце сија изнад планине и небо је ведро и плаво.', 'Sunce sija iznad planine i nebo je vedro i plavo.', 'recenice', 'lake', true),
('Deca se igraju u parku i smeju se glasno i veselo.', 'Деца се играју у парку и смеју се гласно и весело.', 'Deca se igraju u parku i smeju se glasno i veselo.', 'recenice', 'lake', true),
('Mačka sedi na prozoru i gleda u ulicu ispod sebe.', 'Мачка седи на прозору и гледа у улицу испод себе.', 'Macka sedi na prozoru i gleda u ulicu ispod sebe.', 'recenice', 'lake', true),
('Baka kuva čorbu u kuhinji i miris se širi po kući.', 'Бака кува чорбу у кухињи и мирис се шири по кући.', 'Baka kuva corbu u kuhinji i miris se siri po kuci.', 'recenice', 'lake', true),
('Pas trči po travi i nosi štap koji je pronašao.', 'Пас трчи по трави и носи штап који је пронашао.', 'Pas trci po travi i nosi stap koji je pronasao.', 'recenice', 'lake', true),

-- RECENICE — srednje
('Srpski jezik je jedan od najlepših slovenskih jezika na svetu, bogat rečima i izrazima koji opisuju svet oko nas.', 'Српски језик је један од најлепших словенских језика на свету, богат речима и изразима који описују свет око нас.', 'Srpski jezik je jedan od najlepsih slovenskih jezika na svetu, bogat recima i izrazima koji opisuju svet oko nas.', 'recenice', 'srednje', true),
('Praksa čini majstora i to važi za sve što radimo u životu, od muzike do sporta i naučnog istraživanja.', 'Пракса чини мајстора и то важи за све што радимо у животу, од музике до спорта и научног истраживања.', 'Praksa cini majstora i to vazi za sve sto radimo u zivotu, od muzike do sporta i naucnog istrazivanja.', 'recenice', 'srednje', true),
('Knjige su prozori u tuđe živote i zato čitanje proširuje naše razumevanje sveta koji nas okružuje.', 'Књиге су прозори у туђе животе и зато читање проширује наше разумевање света који нас окружује.', 'Knjige su prozori u tudje zivote i zato citanje prosiruje nase razumevanje sveta koji nas okruzuje.', 'recenice', 'srednje', true),
('Planinarenje po srpskim planinama otkriva lepotu prirode i daje telu i umu odmor koji mu je potreban.', 'Планинарење по српским планинама открива лепоту природе и даје телу и уму одмор који му је потребан.', 'Planinarenje po srpskim planinama otkriva lepotu prirode i daje telu i umu odmor koji mu je potreban.', 'recenice', 'srednje', true),
('Moderna tehnologija menja način na koji komuniciramo, učimo i radimo, donoseći i prednosti i izazove.', 'Модерна технологија мења начин на који комуницирамо, учимо и радимо, доносећи и предности и изазове.', 'Moderna tehnologija menja nacin na koji komuniciramo, ucimo i radimo, donoseci i prednosti i izazove.', 'recenice', 'srednje', true),
('Svaki grad ima svoju priču upisanu u kamenu starih ulica i lica ljudi koji ga svakodnevno prolaze.', 'Сваки град има своју причу уписану у камену старих улица и лица људи који га свакодневно пролазе.', 'Svaki grad ima svoju pricu upisanu u kamenu starih ulica i lica ljudi koji ga svakodnevno prolaze.', 'recenice', 'srednje', true),
('Muzika nema granica i spaja ljude različitih kultura i porekla oko zajedničke ljubavi prema zvuku.', 'Музика нема граница и спаја људе различитих култура и порекла око заједничке љубави према звуку.', 'Muzika nema granica i spaja ljude razlicitih kultura i porekla oko zajednicke ljubavi prema zvuku.', 'recenice', 'srednje', true),
('Nauka napreduje korak po korak, kroz greške i otkrića, i svaki eksperiment donosi novo znanje.', 'Наука напредује корак по корак, кроз грешке и открића, и сваки експеримент доноси ново знање.', 'Nauka napreduje korak po korak, kroz greske i otkrica, i svaki eksperiment donosi novo znanje.', 'recenice', 'srednje', true),

-- RECENICE — teske
('Digitalizacija obrazovnih sistema postavlja nova pitanja o pedagogiji, pristupu znanju i ulozi nastavnika u savremenom društvu koje se brzo menja.', 'Дигитализација образовних система поставља нова питања о педагогији, приступу знању и улози наставника у савременом друштву које се брзо мења.', 'Digitalizacija obrazovnih sistema postavlja nova pitanja o pedagogiji, pristupu znanju i ulozi nastavnika u savremenom drustvu koje se brzo menja.', 'recenice', 'teske', true),
('Filozofija jezika istražuje odnos između reči, misli i stvarnosti, postavljajući pitanja koja nemaju jednoznačne odgovore ni posle hiljada godina razmišljanja.', 'Филозофија језика истражује однос између речи, мисли и стварности, постављајући питања која немају једнозначне одговоре ни после хиљада година размишљања.', 'Filozofija jezika istrazuje odnos izmedju reci, misli i stvarnosti, postavljajuci pitanja koja nemaju jednoznacne odgovore ni posle hiljada godina razmisljanja.', 'recenice', 'teske', true),
('Arhitektura Beograda odražava burnu istoriju regiona, od osmanskih tragova do secesije i brutalizma, sve u jednom gradu punom kontrasta i energije.', 'Архитектура Београда одражава бурну историју региона, од osmanских трагова до сецесије и брутализма, све у једном граду пуном контраста и енергије.', 'Arhitektura Beograda odrazava burnu istoriju regiona, od osmanskih tragova do secesije i brutalizma, sve u jednom gradu punom kontrasta i energije.', 'recenice', 'teske', true),

-- CITATI — lake
('Ko uči, ne zna dosadu.', 'Ко учи, не зна досаду.', 'Ko uci, ne zna dosadu.', 'citati', 'lake', true),
('Znanje je moć.', 'Знање је моћ.', 'Znanje je moc.', 'citati', 'lake', true),
('Bolje ikad nego nikad.', 'Боље икад него никад.', 'Bolje ikad nego nikad.', 'citati', 'lake', true),
('Rad čini čoveka slobodnim.', 'Рад чини човека слободним.', 'Rad cini coveka slobodnim.', 'citati', 'lake', true),
('Svaki početak je težak.', 'Сваки почетак је тежак.', 'Svaki pocetak je tezak.', 'citati', 'lake', true),

-- CITATI — srednje
('Nije važno koliko puta padneš, već koliko puta ustaneš.', 'Није важно колико пута паднеш, већ колико пута устанеш.', 'Nije vazno koliko puta padnes, vec koliko puta ustanes.', 'citati', 'srednje', true),
('Čovek je mera svih stvari.', 'Човек је мера свих ствари.', 'Covek je mera svih stvari.', 'citati', 'srednje', true),
('Sreća nije cilj, već put kojim hodamo svaki dan.', 'Срећа није циљ, већ пут којим ходамо сваки дан.', 'Sreca nije cilj, vec put kojim hodamo svaki dan.', 'citati', 'srednje', true),
('Samo ludi sanjaju, ali samo hrabri sanjaju naglas.', 'Само луди сањају, али само храбри сањају наглас.', 'Samo ludi sanjaju, ali samo hrabri sanjaju naglas.', 'citati', 'srednje', true),
('Mudrost počinje onda kada prestanemo da mislimo da znamo sve.', 'Мудрост почиње онда када престанемо да мислимо да знамо све.', 'Mudrost pocinje onda kada prestanemo da mislimo da znamo sve.', 'citati', 'srednje', true),
('Učenje je jedino blago koje te prati kroz ceo život bez da ikada nestane.', 'Учење је једино благо које те прати кроз цео живот без да икада нестане.', 'Ucenje je jedino blago koje te prati kroz ceo zivot bez da ikada nestane.', 'citati', 'srednje', true),
('Tišina je najpametniji odgovor onome ko ne zaslužuje tvoje reči.', 'Тишина је најпаметнији одговор ономе ко не заслужује твоје речи.', 'Tisina je najpametniji odgovor onome ko ne zasluzuje tvoje reci.', 'citati', 'srednje', true),

-- CITATI — teske
('Sloboda je mogućnost da biramo naše okove, jer apsolutna sloboda bez odgovornosti nije sloboda već haos koji razara sve što je vredelo izgraditi.', 'Слобода је могућност да бирамо наше окове, јер апсолутна слобода без одговорности није слобода већ хаос који разара све што је вредело изградити.', 'Sloboda je mogucnost da biramo nase okove, jer apsolutna sloboda bez odgovornosti nije sloboda vec haos koji razara sve sto je vredelo izgraditi.', 'citati', 'teske', true),
('Najteže je biti iskren prema sebi samome, jer um uvek pronalazi hiljadu izgovora da zaštiti ego od istine koja boli.', 'Најтеже је бити искрен према себи самоме, јер ум увек проналази хиљаду изговора да заштити его од истине која боли.', 'Najteže je biti iskren prema sebi samome, jer um uvek pronalazi hiljadu izgovora da zastiti ego od istine koja boli.', 'citati', 'teske', true),
('Istorija se ne ponavlja, ali se ritmuje, i onaj ko ne poznaje prošlost osuđen je da ponavlja greške koje su već plaćene mnogo previsoko.', 'Историја се не понавља, али се ритмује, и онај ко не познаје прошлост осуђен је да понавља грешке које су већ плаћене много превисоко.', 'Istorija se ne ponavlja, ali se ritmuje, i onaj ko ne poznaje prosost osudjen je da ponavlja greske koje su vec placene mnogo previsoko.', 'citati', 'teske', true),

-- PRICE — srednje
('Jednog jutra, starac je pronašao na pragu svog doma mali paket bez ikakvog adresanta. Unutra je bila fotografija i kratka beleška: hvala ti za sve. Nikad nije saznao od koga.', 'Једног јутра, старац је пронашао на прагу свог дома мали пакет без иказог адресанта. Унутра је била фотографија и кратка белешка: хвала ти за све. Никад није сазнао од кога.', 'Jednog jutra, starac je pronasao na pragu svog doma mali paket bez ikakvog adresanta. Unutra je bila fotografija i kratka beleska: hvala ti za sve. Nikad nije saznao od koga.', 'price', 'srednje', true),
('Devojčica je svako veče ostavljala parče hleba za mačku ispod stepenica. Zima je bila surova te godine, ali mačka je preživela. U proleće je donela mladunčad na prag, kao zahvalnost.', 'Девојчица је свако вече остављала парче хлеба за мачку испод степеница. Зима је била сурова те године, али мачка је преживела. У пролеће је донела младунчад на праг, као захвалност.', 'Devojcica je svako vece ostavljala parce hleba za macku ispod stepenica. Zima je bila surova te godine, ali macka je prezivela. U prolece je donela mladuncad na prag, kao zahvalnost.', 'price', 'srednje', true),
('Mladi programer je radio do tri ujutro kada je konačno video zašto kod nije radio. Bio je zarez. Samo jedan zarez na pogrešnom mestu. Nasmejao se, ispravio ga i legao da spava.', 'Млади програмер је радио до три ујутро када је коначно видео зашто код није радио. Био је зарез. Само један зарез на погрешном месту. Насмејао се, исправио га и легао да спава.', 'Mladi programer je radio do tri ujutro kada je konacno video zasto kod nije radio. Bio je zarez. Samo jedan zarez na pogresnom mestu. Nasmejao se, ispravio ga i legao da spava.', 'price', 'srednje', true),
('Na pijaci u Nišu, stara žena je prodavala paprike. Jedan čovek ih je gledao dugo, a onda je pitao koliko koštaju. Rekla je: uzmi koliko ti treba, plati koliko možeš. I on je platio više nego što je tražila.', 'На пијаци у Нишу, стара жена је продавала паприке. Један човек их је гледао дуго, а онда је питао колико коштају. Рекла је: узми колико ти треба, плати колико можеш. И он је платио више него што је тражила.', 'Na pijaci u Nisu, stara zena je prodavala paprike. Jedan covek ih je gledao dugo, a onda je pitao koliko kostaju. Rekla je: uzmi koliko ti treba, plati koliko mozes. I on je platio vise nego sto je trazila.', 'price', 'srednje', true),

-- PRICE — teske
('Biblioteka je bila stara i prašnjava, ali Marko ju je voleo više od sveg mesta u gradu. Svake subote bi dolazio, birao jednu knjigu nasumice i čitao je do zatvaranja. Bibliotekarka ga je poznavala po imenu, ali nikad nije pitala šta traži. Znala je da ko zaista traži — ne treba mu pomoć da pronađe.', 'Библиотека је била стара и прашњава, али Марко ју је волео више од свег места у граду. Сваке суботе би долазио, бирао једну књигу насумице и читао је до затварања. Библиотекарка га је познавала по имену, али никад није питала шта тражи. Знала је да ко заиста тражи — не треба му помоћ да пронађе.', 'Biblioteka je bila stara i prasnjava, ali Marko ju je voleo vise od sveg mesta u gradu. Svake subote bi dolazio, birao jednu knjigu nasumice i citao je do zatvaranja. Bibliotekarka ga je poznavala po imenu, ali nikad nije pitala sta trazi. Znala je da ko zaista trazi — ne treba mu pomoc da pronadje.', 'price', 'teske', true),
('Voz je kasnio tri sata i Ana je sedela na peronu sa koferom koji je bio pretežak za ono što je u njemu bilo. Nije bilo stvari. Bila su pisma. Svako pismo koje je ikad dobila od majke, složena po godinama, od detinjstva do prošle nedelje. Majka je umrla u utorak. Voz je stigao u sredu.', 'Воз је каснио три сата и Ана је седела на перону са кофером који је био претежак за оно што је у њему било. Нису биле ствари. Била су писма. Свако писмо које је икад добила од мајке, сложена по годинама, од детињства до прошле недеље. Мајка је умрла у уторак. Воз је стигао у среду.', 'Voz je kasnio tri sata i Ana je sedela na peronu sa koferom koji je bio pretezak za ono sto je u njemu bilo. Nisu bile stvari. Bila su pisma. Svako pismo koje je ikad dobila od majke, slozena po godinama, od detinjstva do prosle nedelje. Majka je umrla u utorak. Voz je stigao u sredu.', 'price', 'teske', true)

ON CONFLICT DO NOTHING;
